server:
  port: 80
spring:
  datasource:
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mymall?useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations: file:C:/static
logging:
  path: /spring/log
  level:
    com:
      cskaoyan:
        mall:
          mapper: debug
pagehelper:
  helper-dialect: mysql
mybatis:
  type-handlers-package: com.cskaoyan.mall.mybatis

